#ADS Assignment-1
Name: Naveen Kumar.S

Reg No: 20MIS0001

Gmail: naveenkumar.s2020a@vitstudent.ac.in

#Qn: 1.Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.


In [ ]:
name = 'Naveen Kumar'
age = 20
print(f'Hi, My name is {name}.By the way, Age is just a number and My age is {age}.')

Hi, My name is Naveen Kumar.By the way, Age is just a number and My age is 20.


#Qn: 2.X="Datascience is used to extract meaningful insights." Split the string.

In [ ]:
x="Datascience is used to extract meaningful insights."
print(x.split())

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


#Qn: 3.Make a function that gives multiplication of two numbers.

In [ ]:
def multiply(a,b):
  return f'The Multiplication of the given two numbers {a} and {b} is {a*b}.'
a = int(input('Enter the first number a = '))
b = int(input('Enter the second number to be multiplied with a that is b = '))
print(multiply(a,b))

Enter the first number a = 3
Enter the second number to be multiplied with a that is b = 3
The Multiplication of the given two numbers 3 and 3 is 9.


#Qn: 4. Create a Dictionary of 5 States with their capitals. Also print the keys and values.

In [ ]:
state_capitals = {'Maharashtra': 'Mumbai',
'Karnataka': 'Bengaluru',
'Tamil Nadu': 'Chennai',
'Rajasthan': 'Jaipur',
'Kerala': 'Thiruvananthapuram'}
print(state_capitals)

{'Maharashtra': 'Mumbai', 'Karnataka': 'Bengaluru', 'Tamil Nadu': 'Chennai', 'Rajasthan': 'Jaipur', 'Kerala': 'Thiruvananthapuram'}


#Qn: 5. Create a list of 1000 numbers using range function.

In [ ]:
numbers_list = list(range(1000))
print(numbers_list[990:])

[990, 991, 992, 993, 994, 995, 996, 997, 998, 999]


#Qn: 6.Create an identity matrix of dimension 4 by 4.

In [ ]:
import numpy as np
matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#Qn: 7.  Create a 3x3 matrix with values ranging from 1 to 9.

In [ ]:
import numpy as np
matrix1 = np.arange(1,10).reshape(3,3)
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#Qn: 8. Create 2 similar dimensional array and perform sum on them.

In [ ]:
import numpy as np
array1 = np.arange(10).reshape(2,5)
array2 = np.arange(10).reshape(2,5)
sum = array1 + array2
print(sum)


[[ 0  2  4  6  8]
 [10 12 14 16 18]]


#Qn: 9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive).

In [ ]:
import pandas as pd
dates = pd.date_range(start='2023-02-01',end='2023-03-01')
print(dates)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


#Qn : 10.  Given a dictionary, convert it into corresponding dataframe and display it, dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [ ]:
import pandas as pd
dictionary = {
    'Brand': ['Maruti','Renault','Hyndai'],
    'Sales': [250,200,240]
              }
dictionary_data = pd.DataFrame(dictionary)
print(dictionary_data)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
